name: Daily script

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Print Secrets
        run: |
          echo "My Secret Key 1: ${{ secrets.USER_EMAIL }}"
          echo "My Secret Key 2: ${{ secrets.USER_PASSWORD }}"

      - name: Run daily script
        env:
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
          USER_PASSWORD: ${{ secrets.USER_PASSWORD }}  
        run: python main.py
        
#       - name: send email
#         uses: dawidd6/action-send-mail@v2
#         with:
#           server_address: smtp-mail.outlook.com
#           server_port: 587
#           username: ${{ secrets.SMTP_USERNAME }}
#           password: ${{ secrets.SMTP_PASSWORD }}
#           subject: CSV Report
#           body: Here are the latest JVCs.
#           from: Liam Cottrell <liamcottrell1996@hotmail.co.uk>
#           to: liamcottrell1996@hotmail.co.uk
#           attachments: |
#             ./new_df.csv

      - name: commit and push changes
        run: |
          git config user.email "liamcottrell1996@hotmail.co.uk"
          git config user.name "Liam Cottrell"
          git add . 
          git commit -m "latest JVC run"
          git push

